# Generated by Django 5.1.5 on 2025-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
