# Generated by Django 5.1.5 on 2025-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_profile_first_name_student_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
