# Generated by Django 5.1.5 on 2025-01-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sciences', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoqlama_user', to='users.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciences.exam'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballar', to='users.student'),
        ),
        migrations.AddField(
            model_name='sciences',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='sciences.classes'),
        ),
        migrations.AddField(
            model_name='sciences',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanlar', to='users.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='sciences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballar', to='sciences.sciences'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sciences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imtihonlar', to='sciences.sciences'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sciences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoqlama_fan', to='sciences.sciences'),
        ),
    ]
